# Generated by Django 3.2.6 on 2021-08-19 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'dias',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField(unique=True)),
                ('tema', models.CharField(max_length=256)),
                ('agenda', models.TextField(blank=True, max_length=2000, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('zoom_uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('zoom_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('zoom_start_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('zoom_join_url', models.URLField(blank=True, null=True)),
                ('usa_codigo_acceso', models.BooleanField(default=False)),
                ('usa_sala_espera', models.BooleanField(default=True)),
                ('codigo_acceso', models.CharField(blank=True, max_length=8)),
                ('es_recurrente', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Anulada'), (1, 'Nueva'), (2, 'Aprobada'), (3, 'Rechazada')], default=1)),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('centros', models.ManyToManyField(to='catalogos.Centro')),
                ('dias', models.ManyToManyField(to='solicitudes.Dia')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.sala')),
                ('usuario_grabacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'solicitudes',
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ocurrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_id', models.PositiveBigIntegerField()),
                ('fecha', models.DateField()),
                ('duracion', models.PositiveSmallIntegerField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name_plural': 'ocurrencias',
            },
        ),
    ]
