# Generated by Django 3.2.9 on 2021-12-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_instructivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='motivo_rechazo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Salas Llenas'), (2, 'Mantenimiento de la RED')], null=True),
        ),
    ]
