# Generated by Django 3.2.4 on 2021-07-27 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.CharField(max_length=8, unique=True)),
                ('id_direccion', models.CharField(max_length=4)),
                ('id_centro', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=64)),
                ('estado', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'areas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_centro', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=128)),
                ('estado', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'centros',
                'ordering': ['id_centro'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_id', models.SlugField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=64)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Pendiente'), (99, 'N/A')], default=1)),
                ('privada', models.BooleanField(default=False)),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'salas',
                'ordering': ['nombre'],
            },
        ),
    ]
